# Generated by Django 4.1.4 on 2023-02-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='date_of_purchase',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
