# Generated by Django 4.1.4 on 2023-01-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='color',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='productmodel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='productname',
            field=models.CharField(max_length=100),
        ),
    ]
